// src/react/components/MobileUI.tsx
import { useState, useRef } from 'react'
import type { TocItem } from '../../core/types.js'
import type { MobilePanel, SearchState } from '../types.js'
import { TocTree } from './TocTree'
import { SearchResultList } from './SearchResultList'
import { SvgIcon } from './SvgIcon'

type MobileUIProps = {
  barVisible: boolean
  activePanel: MobilePanel | null
  onTogglePanel: (panel: MobilePanel) => void
  onClosePanel: () => void
  
  // Data props
  toc: TocItem[]
  search: SearchState
  status: 'idle' | 'ready' | 'opening' | 'error'
  errorText: string
  sectionLabel: string
  displayedPercent: number
  darkMode: boolean
  fontSize: number
  
  // Actions
  onTocSelect: (href?: string) => void
  
  onSearch: (query: string) => void
  onSearchQueryChange: (query: string) => void
  onSearchOptionChange: (opt: Partial<SearchState['options']>) => void
  onCancelSearch: () => void
  onSearchResultSelect: (cfi: string) => void
  
  onSeekStart: () => void
  onSeekChange: (val: number) => void
  onSeekEnd: (val: number) => void
  onSeekCommit: (val: number) => void
  
  onToggleDarkMode: (val: boolean) => void
  onFontSizeChange: (val: number) => void
}

/**
 * 移动端 UI 组件
 * 包含底部导航栏和弹出面板
 */
export const MobileUI = ({
  barVisible,
  activePanel,
  onTogglePanel,
  onClosePanel,
  toc,
  search,
  status,
  errorText,
  sectionLabel,
  displayedPercent,
  darkMode,
  fontSize,
  onTocSelect,
  onSearch,
  onSearchQueryChange,
  onSearchOptionChange,
  onCancelSearch,
  onSearchResultSelect,
  onSeekStart,
  onSeekChange,
  onSeekEnd,
  onSeekCommit,
  onToggleDarkMode,
  onFontSizeChange,
}: MobileUIProps) => {
  const mobileTitle = activePanel === 'menu' ? '目录' : activePanel === 'search' ? '搜索' : activePanel === 'progress' ? '进度' : activePanel === 'theme' ? '明暗' : activePanel === 'font' ? '字号' : ''

  const [tooltip, setTooltip] = useState<{ text: string, left: number } | null>(null)
  const timerRef = useRef<number | null>(null)

  const handleTouchStart = (e: React.TouchEvent, text: string) => {
    const rect = e.currentTarget.getBoundingClientRect()
    // 长按 500ms 后显示提示
    timerRef.current = window.setTimeout(() => {
      setTooltip({
        text,
        left: rect.left + rect.width / 2
      })
    }, 500)
  }

  const handleTouchEnd = () => {
    if (timerRef.current) {
      clearTimeout(timerRef.current)
      timerRef.current = null
    }
    setTooltip(null)
  }

  return (
    <>
      <div className={`epub-reader__mbar ${barVisible ? 'is-visible' : ''}`}>
        {tooltip && (
          <div 
            className="epub-reader__tooltip" 
            style={{ 
              position: 'fixed', 
              bottom: '60px', // 位于工具栏上方
              left: tooltip.left,
              transform: 'translateX(-50%)',
              background: 'rgba(0,0,0,0.8)',
              color: '#fff',
              padding: '4px 8px',
              borderRadius: '4px',
              fontSize: '12px',
              pointerEvents: 'none',
              zIndex: 1000,
              whiteSpace: 'nowrap'
            }}
          >
            {tooltip.text}
          </div>
        )}
        <button 
          type="button" 
          className="epub-reader__btn" 
          onClick={() => onTogglePanel('menu')} 
          aria-pressed={activePanel === 'menu'}
          onTouchStart={(e) => handleTouchStart(e, '目录')}
          onTouchEnd={handleTouchEnd}
          onTouchCancel={handleTouchEnd}
          title="目录"
        >
          <SvgIcon name="list" />
        </button>
        <button 
          type="button" 
          className="epub-reader__btn" 
          onClick={() => onTogglePanel('search')} 
          aria-pressed={activePanel === 'search'}
          onTouchStart={(e) => handleTouchStart(e, '搜索')}
          onTouchEnd={handleTouchEnd}
          onTouchCancel={handleTouchEnd}
          title="搜索"
        >
          <SvgIcon name="search" />
        </button>
        <button 
          type="button" 
          className="epub-reader__btn" 
          onClick={() => onTogglePanel('progress')} 
          aria-pressed={activePanel === 'progress'}
          onTouchStart={(e) => handleTouchStart(e, '进度')}
          onTouchEnd={handleTouchEnd}
          onTouchCancel={handleTouchEnd}
          title="进度"
        >
          <SvgIcon name="sliders" />
        </button>
        <button 
          type="button" 
          className="epub-reader__btn" 
          onClick={() => onTogglePanel('theme')} 
          aria-pressed={activePanel === 'theme'}
          onTouchStart={(e) => handleTouchStart(e, '明暗')}
          onTouchEnd={handleTouchEnd}
          onTouchCancel={handleTouchEnd}
          title="明暗"
        >
          <SvgIcon name="sun" />
        </button>
        <button 
          type="button" 
          className="epub-reader__btn" 
          onClick={() => onTogglePanel('font')} 
          aria-pressed={activePanel === 'font'}
          onTouchStart={(e) => handleTouchStart(e, '字号')}
          onTouchEnd={handleTouchEnd}
          onTouchCancel={handleTouchEnd}
          title="字号"
        >
          <SvgIcon name="type" />
        </button>
      </div>

      {activePanel ? <div className="epub-reader__moverlay" onClick={onClosePanel} /> : null}

      <div className={`epub-reader__msheet ${activePanel ? 'is-open' : ''}`} aria-hidden={!activePanel}>
        <div className="epub-reader__msheet-header">
          <div className="epub-reader__msheet-title">{mobileTitle}</div>
          <button type="button" className="epub-reader__btn" onClick={onClosePanel}>
            <SvgIcon name="x" />
          </button>
        </div>
        <div className="epub-reader__msheet-body">
          {activePanel === 'menu' ? (
            toc.length ? (
              <TocTree
                items={toc}
                onSelect={(href) => {
                  onTocSelect(href)
                  onClosePanel()
                }}
              />
            ) : (
              <div className="epub-reader__empty">未找到目录</div>
            )
          ) : null}

          {activePanel === 'search' ? (
            <>
              <div className="epub-reader__field">
                <input
                  className="epub-reader__input"
                  placeholder="输入关键词"
                  value={search.query}
                  onChange={(e) => {
                    const v = e.target.value
                    onSearchQueryChange(v)
                    if (!v.trim()) onSearch('')
                  }}
                  disabled={status !== 'ready'}
                  onKeyDown={(e) => {
                    if (e.key === 'Enter') onSearch(search.query)
                  }}
                />
                <button type="button" className="epub-reader__btn" onClick={() => onSearch(search.query)} disabled={status !== 'ready'}>
                  搜索
                </button>
              </div>

              <div className="epub-reader__checks">
                <label className="epub-reader__check">
                  <input
                    type="checkbox"
                    checked={Boolean(search.options.matchCase)}
                    onChange={(e) => onSearchOptionChange({ matchCase: e.target.checked })}
                  />
                  区分大小写
                </label>
                <label className="epub-reader__check">
                  <input
                    type="checkbox"
                    checked={Boolean(search.options.wholeWords)}
                    onChange={(e) => onSearchOptionChange({ wholeWords: e.target.checked })}
                  />
                  全词匹配
                </label>
                <label className="epub-reader__check">
                  <input
                    type="checkbox"
                    checked={Boolean(search.options.matchDiacritics)}
                    onChange={(e) => onSearchOptionChange({ matchDiacritics: e.target.checked })}
                  />
                  区分变音
                </label>
              </div>

              <div className="epub-reader__meta">
                <span>进度 {search.progressPercent}%</span>
                {search.searching ? <span>搜索中…</span> : null}
                {search.searching ? (
                  <button type="button" className="epub-reader__link" onClick={onCancelSearch}>
                    取消
                  </button>
                ) : null}
              </div>

              {search.results.length ? (
                <SearchResultList results={search.results} onSelect={onSearchResultSelect} />
              ) : (
                <div className="epub-reader__empty">{search.query.trim() ? '无匹配结果' : '请输入关键词'}</div>
              )}
            </>
          ) : null}

          {activePanel === 'progress' ? (
            <>
              <div className="epub-reader__meta">
                <span className="epub-reader__status">
                  {status === 'error' ? errorText || '错误' : status === 'opening' ? '正在打开…' : ''}
                </span>
                {sectionLabel ? <span>{sectionLabel}</span> : null}
              </div>
              <div className="epub-reader__mprogress">
                <input
                  className="epub-reader__range"
                  type="range"
                  min={0}
                  max={100}
                  step={1}
                  value={displayedPercent}
                  onChange={(e) => {
                    onSeekStart()
                    onSeekChange(Number(e.target.value))
                  }}
                  onPointerUp={(e) => {
                    const v = Number((e.target as HTMLInputElement).value)
                    onSeekEnd(v)
                  }}
                  onKeyUp={(e) => {
                    if (e.key !== 'Enter') return
                    const v = Number((e.target as HTMLInputElement).value)
                    onSeekCommit(v)
                  }}
                />
                <div className="epub-reader__mprogress-percent">{displayedPercent}%</div>
              </div>
            </>
          ) : null}

          {activePanel === 'theme' ? (
            <button type="button" className="epub-reader__btn" onClick={() => onToggleDarkMode(!darkMode)}>
              {darkMode ? '切换到亮色' : '切换到暗黑'}
            </button>
          ) : null}

          {activePanel === 'font' ? (
            <div className="epub-reader__mfont">
              <button type="button" className="epub-reader__btn" onClick={() => onFontSizeChange(fontSize - 10)}>
                A-
              </button>
              <div className="epub-reader__font">{fontSize}%</div>
              <button type="button" className="epub-reader__btn" onClick={() => onFontSizeChange(fontSize + 10)}>
                A+
              </button>
            </div>
          ) : null}
        </div>
      </div>
    </>
  )
}

// src/vue/components/MobileUI.vue
<script setup lang="ts">
import { computed, ref } from 'vue'
import type { TocItem, SearchOptions, SearchResult } from '../../core/types'
import TocTree from './TocTree.vue'
import SearchResultList from './SearchResultList.vue'
import SvgIcon from './SvgIcon.vue'
import type { MobilePanel } from '../types'

const props = defineProps<{
  barVisible: boolean
  activePanel: MobilePanel | null
  
  // Data
  toc: TocItem[]
  status: 'idle' | 'ready' | 'opening' | 'error'
  errorText: string
  sectionLabel: string
  displayedPercent: number
  darkMode: boolean
  fontSize: number
  
  // Search Data
  searchQuery: string
  searchOptions: SearchOptions
  searchProgressPercent: number
  searching: boolean
  searchResults: SearchResult[]
}>()

const emit = defineEmits<{
  (e: 'togglePanel', panel: MobilePanel): void
  (e: 'closePanel'): void
  
  (e: 'tocSelect', href?: string): void
  
  (e: 'search', query: string): void
  (e: 'update:searchQuery', val: string): void
  (e: 'update:searchOptions', val: Partial<SearchOptions>): void
  (e: 'cancelSearch'): void
  (e: 'searchResultSelect', cfi: string): void
  
  (e: 'seekStart'): void
  (e: 'seekChange', val: number): void
  (e: 'seekEnd', val: number): void
  (e: 'seekCommit', val: number): void
  
  (e: 'toggleDarkMode', val: boolean): void
  (e: 'changeFontSize', val: number): void
}>()

const mobileTitle = computed(() => {
  switch (props.activePanel) {
    case 'menu': return '目录'
    case 'search': return '搜索'
    case 'progress': return '进度'
    case 'theme': return '明暗'
    case 'font': return '字号'
    default: return ''
  }
})

const updateSearchOption = (key: keyof SearchOptions, value: boolean) => {
  emit('update:searchOptions', { [key]: value })
}

const tooltip = ref<{ text: string, left: number } | null>(null)
let timer: number | null = null

const handleTouchStart = (e: TouchEvent, text: string) => {
  const target = e.currentTarget as HTMLElement
  const rect = target.getBoundingClientRect()
  timer = window.setTimeout(() => {
    tooltip.value = {
      text,
      left: rect.left + rect.width / 2
    }
  }, 500)
}

const handleTouchEnd = () => {
  if (timer) {
    clearTimeout(timer)
    timer = null
  }
  tooltip.value = null
}
</script>

<template>
  <div>
    <div :class="['epub-reader__mbar', { 'is-visible': barVisible }]">
      <div 
        v-if="tooltip"
        class="epub-reader__tooltip"
        :style="{
          position: 'fixed',
          bottom: '60px',
          left: `${tooltip.left}px`,
          transform: 'translateX(-50%)',
          background: 'rgba(0,0,0,0.8)',
          color: '#fff',
          padding: '4px 8px',
          borderRadius: '4px',
          fontSize: '12px',
          pointerEvents: 'none',
          zIndex: 1000,
          whiteSpace: 'nowrap'
        }"
      >
        {{ tooltip.text }}
      </div>
      <button 
        type="button" 
        class="epub-reader__btn" 
        :aria-pressed="activePanel === 'menu'" 
        @click="emit('togglePanel', 'menu')"
        @touchstart="(e) => handleTouchStart(e, '目录')"
        @touchend="handleTouchEnd"
        @touchcancel="handleTouchEnd"
        title="目录"
      >
        <SvgIcon name="list" />
      </button>
      <button 
        type="button" 
        class="epub-reader__btn" 
        :aria-pressed="activePanel === 'search'" 
        @click="emit('togglePanel', 'search')"
        @touchstart="(e) => handleTouchStart(e, '搜索')"
        @touchend="handleTouchEnd"
        @touchcancel="handleTouchEnd"
        title="搜索"
      >
        <SvgIcon name="search" />
      </button>
      <button 
        type="button" 
        class="epub-reader__btn" 
        :aria-pressed="activePanel === 'progress'" 
        @click="emit('togglePanel', 'progress')"
        @touchstart="(e) => handleTouchStart(e, '进度')"
        @touchend="handleTouchEnd"
        @touchcancel="handleTouchEnd"
        title="进度"
      >
        <SvgIcon name="sliders" />
      </button>
      <button 
        type="button" 
        class="epub-reader__btn" 
        :aria-pressed="activePanel === 'theme'" 
        @click="emit('togglePanel', 'theme')"
        @touchstart="(e) => handleTouchStart(e, '明暗')"
        @touchend="handleTouchEnd"
        @touchcancel="handleTouchEnd"
        title="明暗"
      >
        <SvgIcon name="sun" />
      </button>
      <button 
        type="button" 
        class="epub-reader__btn" 
        :aria-pressed="activePanel === 'font'" 
        @click="emit('togglePanel', 'font')"
        @touchstart="(e) => handleTouchStart(e, '字号')"
        @touchend="handleTouchEnd"
        @touchcancel="handleTouchEnd"
        title="字号"
      >
        <SvgIcon name="type" />
      </button>
    </div>

    <div v-if="activePanel" class="epub-reader__moverlay" @click="emit('closePanel')" />

    <div :class="['epub-reader__msheet', { 'is-open': activePanel }]" :aria-hidden="!activePanel">
      <div class="epub-reader__msheet-header">
        <div class="epub-reader__msheet-title">{{ mobileTitle }}</div>
        <button type="button" class="epub-reader__btn" @click="emit('closePanel')">
          <SvgIcon name="x" />
        </button>
      </div>
      <div class="epub-reader__msheet-body">
        <template v-if="activePanel === 'menu'">
          <TocTree
            v-if="toc.length"
            :items="toc"
            @select="(href) => {
              emit('tocSelect', href)
              emit('closePanel')
            }"
          />
          <div v-else class="epub-reader__empty">未找到目录</div>
        </template>

        <template v-if="activePanel === 'search'">
          <div class="epub-reader__field">
            <input
              class="epub-reader__input"
              placeholder="输入关键词"
              :value="searchQuery"
              :disabled="status !== 'ready'"
              @input="(e: any) => {
                const v = e.target.value
                emit('update:searchQuery', v)
                if (!v.trim()) emit('search', '')
              }"
              @keydown.enter="emit('search', searchQuery)"
            />
            <button type="button" class="epub-reader__btn" :disabled="status !== 'ready'" @click="emit('search', searchQuery)">
              搜索
            </button>
          </div>

          <div class="epub-reader__checks">
            <label class="epub-reader__check">
              <input
                type="checkbox"
                :checked="Boolean(searchOptions.matchCase)"
                @change="(e: any) => updateSearchOption('matchCase', e.target.checked)"
              />
              区分大小写
            </label>
            <label class="epub-reader__check">
              <input
                type="checkbox"
                :checked="Boolean(searchOptions.wholeWords)"
                @change="(e: any) => updateSearchOption('wholeWords', e.target.checked)"
              />
              全词匹配
            </label>
            <label class="epub-reader__check">
              <input
                type="checkbox"
                :checked="Boolean(searchOptions.matchDiacritics)"
                @change="(e: any) => updateSearchOption('matchDiacritics', e.target.checked)"
              />
              区分变音
            </label>
          </div>

          <div class="epub-reader__meta">
            <span>进度 {{ searchProgressPercent }}%</span>
            <span v-if="searching">搜索中…</span>
            <button v-if="searching" type="button" class="epub-reader__link" @click="emit('cancelSearch')">
              取消
            </button>
          </div>

          <SearchResultList v-if="searchResults.length" :results="searchResults" @select="(cfi) => emit('searchResultSelect', cfi)" />
          <div v-else class="epub-reader__empty">{{ searchQuery.trim() ? '无匹配结果' : '请输入关键词' }}</div>
        </template>

        <template v-if="activePanel === 'progress'">
          <div class="epub-reader__meta">
            <span class="epub-reader__status">
              {{ status === 'error' ? errorText || '错误' : status === 'opening' ? '正在打开…' : '' }}
            </span>
            <span v-if="sectionLabel">{{ sectionLabel }}</span>
          </div>
          <div class="epub-reader__mprogress">
            <input
              class="epub-reader__range"
              type="range"
              :min="0"
              :max="100"
              :step="1"
              :value="displayedPercent"
              @input="(e: any) => {
                emit('seekStart')
                emit('seekChange', Number(e.target.value))
              }"
              @pointerup="(e: any) => emit('seekEnd', Number(e.target.value))"
              @keyup.enter="(e: any) => emit('seekCommit', Number(e.target.value))"
            />
            <div class="epub-reader__mprogress-percent">{{ displayedPercent }}%</div>
          </div>
        </template>

        <template v-if="activePanel === 'theme'">
          <button type="button" class="epub-reader__btn" @click="emit('toggleDarkMode', !darkMode)">
            {{ darkMode ? '切换到亮色' : '切换到暗黑' }}
          </button>
        </template>

        <template v-if="activePanel === 'font'">
          <div class="epub-reader__mfont">
            <button type="button" class="epub-reader__btn" @click="emit('changeFontSize', fontSize - 10)">
              A-
            </button>
            <div class="epub-reader__font">{{ fontSize }}%</div>
            <button type="button" class="epub-reader__btn" @click="emit('changeFontSize', fontSize + 10)">
              A+
            </button>
          </div>
        </template>
      </div>
    </div>
  </div>
</template>
