// src/vue/components/TocDrawer.vue
<script setup lang="ts">
import type { TocItem } from '../../core/types'
import TocTree from './TocTree.vue'
import SvgIcon from './SvgIcon.vue'

defineProps<{
  isOpen: boolean
  toc: TocItem[]
}>()

const emit = defineEmits<{
  (e: 'close'): void
  (e: 'select', href?: string): void
}>()
</script>

<template>
  <aside :class="['ebook-reader__drawer', { 'is-open': isOpen }]" :aria-hidden="!isOpen">
    <div class="ebook-reader__drawer-header">
      <div class="ebook-reader__drawer-title">目录</div>
      <button type="button" class="ebook-reader__btn" @click="emit('close')">
        <SvgIcon name="x" />
      </button>
    </div>
    <div class="ebook-reader__drawer-body">
      <TocTree
        v-if="toc.length"
        :items="toc"
        @select="(href) => {
          emit('select', href)
          emit('close')
        }"
      />
      <div v-else class="ebook-reader__empty">未找到目录</div>
    </div>
  </aside>
</template>

// src/react/components/TocDrawer.tsx
import type { TocItem } from '../../core/types.js'
import { TocTree } from './TocTree'
import { SvgIcon } from './SvgIcon'

type TocDrawerProps = {
  isOpen: boolean
  onClose: () => void
  toc: TocItem[]
  onSelect: (href?: string) => void
}

/**
 * 目录侧边栏组件
 */
export const TocDrawer = ({ isOpen, onClose, toc, onSelect }: TocDrawerProps) => {
  return (
    <aside className={`ebook-reader__drawer ${isOpen ? 'is-open' : ''}`} aria-hidden={!isOpen}>
      <div className="ebook-reader__drawer-header">
        <div className="ebook-reader__drawer-title">目录</div>
        <button type="button" className="ebook-reader__btn" onClick={onClose}>
          <SvgIcon name="x" />
        </button>
      </div>
      <div className="ebook-reader__drawer-body">
        {toc.length ? (
          <TocTree
            items={toc}
            onSelect={(href) => {
              onSelect(href)
              onClose()
            }}
          />
        ) : (
          <div className="ebook-reader__empty">未找到目录</div>
        )}
      </div>
    </aside>
  )
}
